In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import cross_val_score
from xgboost import XGBRegressor

def score_dataset(X, y, model=XGBRegressor(random_state=0)):
    # Label encoding for categoricals
    for colname in X.select_dtypes(["category", "object"]):
        X[colname], _ = X[colname].factorize()
    score = cross_val_score(
        model, X, y, cv=5, scoring="neg_mean_squared_log_error",
    )
    score = -1 * score.mean()
    score = np.sqrt(score)
    return score


# Load data, separate predictors and target
df = pd.read_csv("../datasets/fe-course-data/ames.csv")
X = df.copy()
y = X.pop("SalePrice")

In [2]:
X_1 = pd.DataFrame()

X_1["LivLotRatio"] = X.GrLivArea / X.LotArea
X_1["Spaciousness"] = (X.FirstFlrSF + X.SecondFlrSF) / X.TotRmsAbvGrd
X_1["TotalOutsideSF"] = sum(X[_] for _ in ['WoodDeckSF', 'OpenPorchSF', 
                                           'EnclosedPorch', 'Threeseasonporch',
                                           'ScreenPorch'])

X_1

      LivLotRatio  Spaciousness  TotalOutsideSF
0        0.052125    236.571429           272.0
1        0.077095    179.200000           260.0
2        0.093152    221.500000           429.0
3        0.189068    263.750000             0.0
4        0.117787    271.500000           246.0
...           ...           ...             ...
2925     0.126370    167.166667           120.0
2926     0.101519    180.400000           164.0
2927     0.092903    161.666667           112.0
2928     0.138761    231.500000           278.0
2929     0.207749    222.222222           238.0

[2930 rows x 3 columns]

In [3]:
# We discovered an interaction between `BldgType` and `GrLivArea` in Exercise 2. 
# Now create their interaction features.

# One-hot encode BldgType,  using `prefix="Bldg"`
X_2 = pd.get_dummies(X.BldgType, prefix="Bldg") 

# Multiply by the continous feature
X_2 = X_2.mul(X.GrLivArea, axis=0)
X_2

      Bldg_Duplex  Bldg_OneFam  Bldg_Twnhs  Bldg_TwnhsE  Bldg_TwoFmCon
0             0.0       1656.0         0.0          0.0            0.0
1             0.0        896.0         0.0          0.0            0.0
2             0.0       1329.0         0.0          0.0            0.0
3             0.0       2110.0         0.0          0.0            0.0
4             0.0       1629.0         0.0          0.0            0.0
...           ...          ...         ...          ...            ...
2925          0.0       1003.0         0.0          0.0            0.0
2926          0.0        902.0         0.0          0.0            0.0
2927          0.0        970.0         0.0          0.0            0.0
2928          0.0       1389.0         0.0          0.0            0.0
2929          0.0       2000.0         0.0          0.0            0.0

[2930 rows x 5 columns]

In [4]:
# Create a feature PorchTypes that counts how many of the following are greater than 0.0:
# - WoodDeckSF
# - OpenPorchSF
# - EnclosedPorch
# - Threeseasonporch
# - ScreenPorch

X_3 = pd.DataFrame()

porch_features = ['WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', 'Threeseasonporch', 'ScreenPorch']
X_3["PorchTypes"] = X[porch_features].gt(0.0).sum(axis=1)

X_3

      PorchTypes
0              2
1              2
2              2
3              0
4              2
...          ...
2925           1
2926           1
2927           2
2928           2
2929           2

[2930 rows x 1 columns]

In [5]:
X.MSSubClass.unique()

array(['One_Story_1946_and_Newer_All_Styles', 'Two_Story_1946_and_Newer',
       'One_Story_PUD_1946_and_Newer',
       'One_and_Half_Story_Finished_All_Ages', 'Split_Foyer',
       'Two_Story_PUD_1946_and_Newer', 'Split_or_Multilevel',
       'One_Story_1945_and_Older', 'Duplex_All_Styles_and_Ages',
       'Two_Family_conversion_All_Styles_and_Ages',
       'One_and_Half_Story_Unfinished_All_Ages',
       'Two_Story_1945_and_Older', 'Two_and_Half_Story_All_Ages',
       'One_Story_with_Finished_Attic_All_Ages',
       'PUD_Multilevel_Split_Level_Foyer',
       'One_and_Half_Story_PUD_All_Ages'], dtype=object)

In [6]:
# Create a feature containing only these first words by splitting MSSubClass at the first underscore.
# (Hint: In the split method use an argument n=1.)
X_4 = pd.DataFrame()
X_4['MSClass'] = X.MSSubClass.str.split("_", n=1, expand=True)[0]
X_4

     MSClass
0        One
1        One
2        One
3        One
4        Two
...      ...
2925   Split
2926     One
2927   Split
2928     One
2929     Two

[2930 rows x 1 columns]

In [7]:
# Create a feature MedNhbdArea that describes the median of GrLivArea grouped on Neighborhood.
X_5 = pd.DataFrame()
X_5["MedNhbdArea"] = X.groupby('Neighborhood')["GrLivArea"].transform("median")
X_5

      MedNhbdArea
0          1200.0
1          1200.0
2          1200.0
3          1200.0
4          1560.0
...           ...
2925       1282.0
2926       1282.0
2927       1282.0
2928       1282.0
2929       1282.0

[2930 rows x 1 columns]

In [9]:
X_new = X.join([X_1, X_2, X_3, X_4, X_5])
score = score_dataset(X, y) # 0.13954039591355258
score

/opt/conda/lib/python3.11/site-packages/sklearn/utils/_tags.py:354: FutureWarning: The XGBRegressor or classes from which it inherits use `_get_tags` and `_more_tags`. Please define the `__sklearn_tags__` method, or inherit from `sklearn.base.BaseEstimator` and/or other appropriate mixins such as `sklearn.base.TransformerMixin`, `sklearn.base.ClassifierMixin`, `sklearn.base.RegressorMixin`, and `sklearn.base.OutlierMixin`. From scikit-learn 1.7, not defining `__sklearn_tags__` will raise an error.
  warnings.warn(

AttributeError: 'super' object has no attribute '__sklearn_tags__'